[package]
name = "log_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
sqlx = { version = "0.5", features = ["mysql", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["full"] }