CREATE DATABASE IF NOT EXISTS log_database;

USE log_database;

CREATE TABLE IF NOT EXISTS logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hostname VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    log_level VARCHAR(255) NOT NULL,
    message TEXT NOT NULL
);